// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TheRealBest.Infrastructure.Data;

#nullable disable

namespace TheRealBest.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260924202107_AddOwnGoalsAndPenaltiesScored")]
    partial class AddOwnGoalsAndPenaltiesScored
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TheRealBest.Domain.Entities.ActionTypeTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ActionKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action_key");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("label");

                    b.Property<string>("LabelPlural")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("label_plural");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("locale");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_action_type_translations");

                    b.HasIndex("ActionKey", "Locale")
                        .IsUnique()
                        .HasDatabaseName("ix_action_type_translations_action_key_locale");

                    b.ToTable("action_type_translations", (string)null);
                });

            modelBuilder.Entity("TheRealBest.Domain.Entities.Competition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ExternalApiId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("external_api_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<int>("SeasonYear")
                        .HasColumnType("integer")
                        .HasColumnName("season_year");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tier");

                    b.Property<decimal>("TournamentMultiplier")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("tournament_multiplier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_competitions");

                    b.HasIndex("ExternalApiId", "SeasonYear")
                        .IsUnique()
                        .HasDatabaseName("ix_competitions_external_api_id_season_year");

                    b.ToTable("competitions", (string)null);
                });

            modelBuilder.Entity("TheRealBest.Domain.Entities.CompetitionTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("competition_id");

                    b.Property<string>("CountryName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country_name");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("locale");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_competition_translations");

                    b.HasIndex("CompetitionId", "Locale")
                        .IsUnique()
                        .HasDatabaseName("ix_competition_translations_competition_id_locale");

                    b.ToTable("competition_translations", (string)null);
                });

            modelBuilder.Entity("TheRealBest.Domain.Entities.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int?>("AwayScore")
                        .HasColumnType("integer")
                        .HasColumnName("away_score");

                    b.Property<Guid>("AwayTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("away_team_id");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("competition_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ExternalApiId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("external_api_id");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("integer")
                        .HasColumnName("home_score");

                    b.Property<Guid>("HomeTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("home_team_id");

                    b.Property<bool>("IsKnockout")
                        .HasColumnType("boolean")
                        .HasColumnName("is_knockout");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("match_date");

                    b.Property<string>("RoundPhase")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("round_phase");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_matches");

                    b.HasIndex("AwayTeamId")
                        .HasDatabaseName("ix_matches_away_team_id");

                    b.HasIndex("ExternalApiId")
                        .IsUnique()
                        .HasDatabaseName("ix_matches_external_api_id");

                    b.HasIndex("HomeTeamId")
                        .HasDatabaseName("ix_matches_home_team_id");

                    b.HasIndex("CompetitionId", "MatchDate")
                        .HasDatabaseName("ix_matches_competition_id_match_date");

                    b.ToTable("matches", (string)null);
                });

            modelBuilder.Entity("TheRealBest.Domain.Entities.MatchPerformanceScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ActionBreakdownJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("action_breakdown")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<int>("AlgorithmVersion")
                        .HasColumnType("integer")
                        .HasColumnName("algorithm_version");

                    b.Property<decimal>("BaseScore")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("base_score");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("calculated_at");

                    b.Property<decimal>("ClutchMultiplier")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("clutch_multiplier");

                    b.Property<decimal>("ContextMultiplierCombined")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("context_multiplier_combined");

                    b.Property<bool>("CountsTowardsSeason")
                        .HasColumnType("boolean")
                        .HasColumnName("counts_towards_season");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("FinalMps")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("final_mps");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.Property<Guid>("MatchPlayerStatsId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_player_stats_id");

                    b.Property<decimal>("MinutesFactor")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("minutes_factor");

                    b.Property<decimal>("OpponentMultiplier")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("opponent_multiplier");

                    b.Property<string>("PenaltyBreakdownJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("penalty_breakdown")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<decimal>("PositionBaseline")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("position_baseline");

                    b.Property<string>("PositionEvaluated")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("position_evaluated");

                    b.Property<decimal>("SubtotalRaw")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("subtotal_raw");

                    b.Property<decimal>("TournamentMultiplier")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("tournament_multiplier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_match_performance_scores");

                    b.HasIndex("MatchId")
                        .HasDatabaseName("ix_match_performance_scores_match_id");

                    b.HasIndex("MatchPlayerStatsId")
                        .IsUnique()
                        .HasDatabaseName("ix_match_performance_scores_match_player_stats_id");

                    b.HasIndex("PlayerId", "AlgorithmVersion")
                        .HasDatabaseName("ix_match_performance_scores_player_id_algorithm_version");

                    b.HasIndex("PlayerId", "MatchId")
                        .HasDatabaseName("ix_match_performance_scores_player_id_match_id");

                    b.ToTable("match_performance_scores", (string)null);
                });

            modelBuilder.Entity("TheRealBest.Domain.Entities.MatchPlayerStats", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AerialDuelsTotal")
                        .HasColumnType("integer")
                        .HasColumnName("aerial_duels_total");

                    b.Property<int>("AerialDuelsWon")
                        .HasColumnType("integer")
                        .HasColumnName("aerial_duels_won");

                    b.Property<int>("Assists")
                        .HasColumnType("integer")
                        .HasColumnName("assists");

                    b.Property<int>("BallRecoveries")
                        .HasColumnType("integer")
                        .HasColumnName("ball_recoveries");

                    b.Property<int>("BigChancesCreated")
                        .HasColumnType("integer")
                        .HasColumnName("big_chances_created");

                    b.Property<int>("BigChancesMissed")
                        .HasColumnType("integer")
                        .HasColumnName("big_chances_missed");

                    b.Property<int>("Blocks")
                        .HasColumnType("integer")
                        .HasColumnName("blocks");

                    b.Property<bool>("CleanSheet")
                        .HasColumnType("boolean")
                        .HasColumnName("clean_sheet");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DribbledPast")
                        .HasColumnType("integer")
                        .HasColumnName("dribbled_past");

                    b.Property<int>("DribblesAttempted")
                        .HasColumnType("integer")
                        .HasColumnName("dribbles_attempted");

                    b.Property<int>("DribblesSuccess")
                        .HasColumnType("integer")
                        .HasColumnName("dribbles_success");

                    b.Property<int>("DuelsTotal")
                        .HasColumnType("integer")
                        .HasColumnName("duels_total");

                    b.Property<int>("DuelsWon")
                        .HasColumnType("integer")
                        .HasColumnName("duels_won");

                    b.Property<int>("ErrorsLeadingToGoal")
                        .HasColumnType("integer")
                        .HasColumnName("errors_leading_to_goal");

                    b.Property<int>("FoulsCommitted")
                        .HasColumnType("integer")
                        .HasColumnName("fouls_committed");

                    b.Property<int>("FoulsDrawn")
                        .HasColumnType("integer")
                        .HasColumnName("fouls_drawn");

                    b.Property<int>("Goals")
                        .HasColumnType("integer")
                        .HasColumnName("goals");

                    b.Property<int>("GoalsConceded")
                        .HasColumnType("integer")
                        .HasColumnName("goals_conceded");

                    b.Property<int>("Interceptions")
                        .HasColumnType("integer")
                        .HasColumnName("interceptions");

                    b.Property<int>("KeyPasses")
                        .HasColumnType("integer")
                        .HasColumnName("key_passes");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.Property<int>("MinutesPlayed")
                        .HasColumnType("integer")
                        .HasColumnName("minutes_played");

                    b.Property<int>("Offsides")
                        .HasColumnType("integer")
                        .HasColumnName("offsides");

                    b.Property<int>("OwnGoals")
                        .HasColumnType("integer")
                        .HasColumnName("own_goals");

                    b.Property<decimal>("PassAccuracy")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("pass_accuracy");

                    b.Property<int>("PassesAccurate")
                        .HasColumnType("integer")
                        .HasColumnName("passes_accurate");

                    b.Property<int>("PassesTotal")
                        .HasColumnType("integer")
                        .HasColumnName("passes_total");

                    b.Property<int>("PenaltiesCommitted")
                        .HasColumnType("integer")
                        .HasColumnName("penalties_committed");

                    b.Property<int>("PenaltiesMissed")
                        .HasColumnType("integer")
                        .HasColumnName("penalties_missed");

                    b.Property<int>("PenaltiesSaved")
                        .HasColumnType("integer")
                        .HasColumnName("penalties_saved");

                    b.Property<int>("PenaltiesScored")
                        .HasColumnType("integer")
                        .HasColumnName("penalties_scored");

                    b.Property<int>("PenaltiesWon")
                        .HasColumnType("integer")
                        .HasColumnName("penalties_won");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<string>("PositionPlayed")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("position_played");

                    b.Property<int>("ProgressiveCarries")
                        .HasColumnType("integer")
                        .HasColumnName("progressive_carries");

                    b.Property<int>("ProgressivePasses")
                        .HasColumnType("integer")
                        .HasColumnName("progressive_passes");

                    b.Property<int>("RedCards")
                        .HasColumnType("integer")
                        .HasColumnName("red_cards");

                    b.Property<int>("Saves")
                        .HasColumnType("integer")
                        .HasColumnName("saves");

                    b.Property<int>("ShotCreatingActions")
                        .HasColumnType("integer")
                        .HasColumnName("shot_creating_actions");

                    b.Property<int>("ShotsOnTarget")
                        .HasColumnType("integer")
                        .HasColumnName("shots_on_target");

                    b.Property<int>("ShotsTotal")
                        .HasColumnType("integer")
                        .HasColumnName("shots_total");

                    b.Property<int>("TacklesTotal")
                        .HasColumnType("integer")
                        .HasColumnName("tackles_total");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<int>("Touches")
                        .HasColumnType("integer")
                        .HasColumnName("touches");

                    b.Property<int>("Turnovers")
                        .HasColumnType("integer")
                        .HasColumnName("turnovers");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("Xa")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("xa");

                    b.Property<decimal>("Xg")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("xg");

                    b.Property<int>("YellowCards")
                        .HasColumnType("integer")
                        .HasColumnName("yellow_cards");

                    b.HasKey("Id")
                        .HasName("pk_match_player_stats");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("ix_match_player_stats_player_id");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_match_player_stats_team_id");

                    b.HasIndex("MatchId", "PlayerId")
                        .IsUnique()
                        .HasDatabaseName("ix_match_player_stats_match_id_player_id");

                    b.ToTable("match_player_stats", (string)null);
                });

            modelBuilder.Entity("TheRealBest.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("ExternalApiId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("external_api_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nationality");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("photo_url");

                    b.Property<string>("PrimaryPosition")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("primary_position");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_players");

                    b.HasIndex("ExternalApiId")
                        .IsUnique()
                        .HasDatabaseName("ix_players_external_api_id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_players_name");

                    b.HasIndex("PrimaryPosition")
                        .HasDatabaseName("ix_players_primary_position");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("TheRealBest.Domain.Entities.ScoringWeightRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("action_type");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsPenalty")
                        .HasColumnType("boolean")
                        .HasColumnName("is_penalty");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("position");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<decimal>("WeightValue")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("weight_value");

                    b.HasKey("Id")
                        .HasName("pk_scoring_weights");

                    b.HasIndex("Position", "ActionType", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_scoring_weights_position_action_type_version");

                    b.ToTable("scoring_weights", (string)null);
                });

            modelBuilder.Entity("TheRealBest.Domain.Entities.SeasonRanking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("ClutchIndex")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("clutch_index");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("FssScore")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("fss_score");

                    b.Property<bool>("IsRankingEligible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_ranking_eligible");

                    b.Property<decimal>("MpsAverage")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("mps_average");

                    b.Property<decimal>("MpsSumWeighted")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("mps_sum_weighted");

                    b.Property<int>("OverallRank")
                        .HasColumnType("integer")
                        .HasColumnName("overall_rank");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<int>("PositionRank")
                        .HasColumnType("integer")
                        .HasColumnName("position_rank");

                    b.Property<decimal>("PresenceFactor")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("presence_factor");

                    b.Property<DateTime>("RecalculatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recalculated_at");

                    b.Property<int>("SeasonYear")
                        .HasColumnType("integer")
                        .HasColumnName("season_year");

                    b.Property<string>("Top5MatchesJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("top_5_matches")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<int>("TotalMatches")
                        .HasColumnType("integer")
                        .HasColumnName("total_matches");

                    b.Property<int>("TotalMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("total_minutes");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_season_rankings");

                    b.HasIndex("PlayerId", "SeasonYear")
                        .IsUnique()
                        .HasDatabaseName("ix_season_rankings_player_id_season_year");

                    b.HasIndex("SeasonYear", "OverallRank")
                        .HasDatabaseName("ix_season_rankings_season_year_overall_rank")
                        .HasFilter("is_ranking_eligible");

                    b.HasIndex("SeasonYear", "PositionRank")
                        .HasDatabaseName("ix_season_rankings_season_year_position_rank")
                        .HasFilter("is_ranking_eligible");

                    b.ToTable("season_rankings", (string)null);
                });

            modelBuilder.Entity("TheRealBest.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("EloRanking")
                        .HasColumnType("integer")
                        .HasColumnName("elo_ranking");

                    b.Property<string>("ExternalApiId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("external_api_id");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("logo_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("short_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_teams");

                    b.HasIndex("ExternalApiId")
                        .IsUnique()
                        .HasDatabaseName("ix_teams_external_api_id");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("TheRealBest.Domain.Entities.CompetitionTranslation", b =>
                {
                    b.HasOne("TheRealBest.Domain.Entities.Competition", "Competition")
                        .WithMany("Translations")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_competition_translations_competitions_competition_id");

                    b.Navigation("Competition");
                });

            modelBuilder.Entity("TheRealBest.Domain.Entities.Match", b =>
                {
                    b.HasOne("TheRealBest.Domain.Entities.Team", "AwayTeam")
                        .WithMany("AwayMatches")
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_matches_teams_away_team_id");

                    b.HasOne("TheRealBest.Domain.Entities.Competition", "Competition")
                        .WithMany("Matches")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_matches_competitions_competition_id");

                    b.HasOne("TheRealBest.Domain.Entities.Team", "HomeTeam")
                        .WithMany("HomeMatches")
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_matches_teams_home_team_id");

                    b.Navigation("AwayTeam");

                    b.Navigation("Competition");

                    b.Navigation("HomeTeam");
                });

            modelBuilder.Entity("TheRealBest.Domain.Entities.MatchPerformanceScore", b =>
                {
                    b.HasOne("TheRealBest.Domain.Entities.Match", "Match")
                        .WithMany("PerformanceScores")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_match_performance_scores_matches_match_id");

                    b.HasOne("TheRealBest.Domain.Entities.MatchPlayerStats", "MatchPlayerStats")
                        .WithOne("PerformanceScore")
                        .HasForeignKey("TheRealBest.Domain.Entities.MatchPerformanceScore", "MatchPlayerStatsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_match_performance_scores_match_player_stats_match_player_st");

                    b.HasOne("TheRealBest.Domain.Entities.Player", "Player")
                        .WithMany("PerformanceScores")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_match_performance_scores_players_player_id");

                    b.Navigation("Match");

                    b.Navigation("MatchPlayerStats");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("TheRealBest.Domain.Entities.MatchPlayerStats", b =>
                {
                    b.HasOne("TheRealBest.Domain.Entities.Match", "Match")
                        .WithMany("PlayerStats")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_match_player_stats_matches_match_id");

                    b.HasOne("TheRealBest.Domain.Entities.Player", "Player")
                        .WithMany("MatchStats")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_match_player_stats_players_player_id");

                    b.HasOne("TheRealBest.Domain.Entities.Team", "Team")
                        .WithMany("PlayerStats")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_match_player_stats_teams_team_id");

                    b.Navigation("Match");

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("TheRealBest.Domain.Entities.SeasonRanking", b =>
                {
                    b.HasOne("TheRealBest.Domain.Entities.Player", "Player")
                        .WithMany("SeasonRankings")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_season_rankings_players_player_id");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("TheRealBest.Domain.Entities.Competition", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("TheRealBest.Domain.Entities.Match", b =>
                {
                    b.Navigation("PerformanceScores");

                    b.Navigation("PlayerStats");
                });

            modelBuilder.Entity("TheRealBest.Domain.Entities.MatchPlayerStats", b =>
                {
                    b.Navigation("PerformanceScore");
                });

            modelBuilder.Entity("TheRealBest.Domain.Entities.Player", b =>
                {
                    b.Navigation("MatchStats");

                    b.Navigation("PerformanceScores");

                    b.Navigation("SeasonRankings");
                });

            modelBuilder.Entity("TheRealBest.Domain.Entities.Team", b =>
                {
                    b.Navigation("AwayMatches");

                    b.Navigation("HomeMatches");

                    b.Navigation("PlayerStats");
                });
#pragma warning restore 612, 618
        }
    }
}
